#!/usr/bin/env python3

import connexion
from .encoder import JSONEncoder

import argparse
from routes_aggregator.service import Service

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Routes Aggregator API')
    parser.add_argument('config_path', help='Path to configuration file')
    args = parser.parse_args()

    Service(config_path=args.config_path)

    app = connexion.App(__name__, specification_dir='./swagger/')
    app.app.json_encoder = JSONEncoder
    app.add_api('swagger.yaml', arguments={'title': 'No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)'})
    app.run(port=8080)
