# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.route import Route
from swagger_server.models.route_point import RoutePoint
from swagger_server.models.station import Station
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PathItem(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, route: Route=None, departure_station: Station=None, departure_time: str=None, arrival_station: Station=None, arrival_time: str=None, travel_time: str=None, route_points: List[RoutePoint]=None):
        """
        PathItem - a model defined in Swagger

        :param route: The route of this PathItem.
        :type route: Route
        :param departure_station: The departure_station of this PathItem.
        :type departure_station: Station
        :param departure_time: The departure_time of this PathItem.
        :type departure_time: str
        :param arrival_station: The arrival_station of this PathItem.
        :type arrival_station: Station
        :param arrival_time: The arrival_time of this PathItem.
        :type arrival_time: str
        :param travel_time: The travel_time of this PathItem.
        :type travel_time: str
        :param route_points: The route_points of this PathItem.
        :type route_points: List[RoutePoint]
        """
        self.swagger_types = {
            'route': Route,
            'departure_station': Station,
            'departure_time': str,
            'arrival_station': Station,
            'arrival_time': str,
            'travel_time': str,
            'route_points': List[RoutePoint]
        }

        self.attribute_map = {
            'route': 'route',
            'departure_station': 'departure_station',
            'departure_time': 'departure_time',
            'arrival_station': 'arrival_station',
            'arrival_time': 'arrival_time',
            'travel_time': 'travel_time',
            'route_points': 'route_points'
        }

        self._route = route
        self._departure_station = departure_station
        self._departure_time = departure_time
        self._arrival_station = arrival_station
        self._arrival_time = arrival_time
        self._travel_time = travel_time
        self._route_points = route_points

    @classmethod
    def from_dict(cls, dikt) -> 'PathItem':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PathItem of this PathItem.
        :rtype: PathItem
        """
        return deserialize_model(dikt, cls)

    @property
    def route(self) -> Route:
        """
        Gets the route of this PathItem.

        :return: The route of this PathItem.
        :rtype: Route
        """
        return self._route

    @route.setter
    def route(self, route: Route):
        """
        Sets the route of this PathItem.

        :param route: The route of this PathItem.
        :type route: Route
        """

        self._route = route

    @property
    def departure_station(self) -> Station:
        """
        Gets the departure_station of this PathItem.

        :return: The departure_station of this PathItem.
        :rtype: Station
        """
        return self._departure_station

    @departure_station.setter
    def departure_station(self, departure_station: Station):
        """
        Sets the departure_station of this PathItem.

        :param departure_station: The departure_station of this PathItem.
        :type departure_station: Station
        """

        self._departure_station = departure_station

    @property
    def departure_time(self) -> str:
        """
        Gets the departure_time of this PathItem.

        :return: The departure_time of this PathItem.
        :rtype: str
        """
        return self._departure_time

    @departure_time.setter
    def departure_time(self, departure_time: str):
        """
        Sets the departure_time of this PathItem.

        :param departure_time: The departure_time of this PathItem.
        :type departure_time: str
        """

        self._departure_time = departure_time

    @property
    def arrival_station(self) -> Station:
        """
        Gets the arrival_station of this PathItem.

        :return: The arrival_station of this PathItem.
        :rtype: Station
        """
        return self._arrival_station

    @arrival_station.setter
    def arrival_station(self, arrival_station: Station):
        """
        Sets the arrival_station of this PathItem.

        :param arrival_station: The arrival_station of this PathItem.
        :type arrival_station: Station
        """

        self._arrival_station = arrival_station

    @property
    def arrival_time(self) -> str:
        """
        Gets the arrival_time of this PathItem.

        :return: The arrival_time of this PathItem.
        :rtype: str
        """
        return self._arrival_time

    @arrival_time.setter
    def arrival_time(self, arrival_time: str):
        """
        Sets the arrival_time of this PathItem.

        :param arrival_time: The arrival_time of this PathItem.
        :type arrival_time: str
        """

        self._arrival_time = arrival_time

    @property
    def travel_time(self) -> str:
        """
        Gets the travel_time of this PathItem.

        :return: The travel_time of this PathItem.
        :rtype: str
        """
        return self._travel_time

    @travel_time.setter
    def travel_time(self, travel_time: str):
        """
        Sets the travel_time of this PathItem.

        :param travel_time: The travel_time of this PathItem.
        :type travel_time: str
        """

        self._travel_time = travel_time

    @property
    def route_points(self) -> List[RoutePoint]:
        """
        Gets the route_points of this PathItem.

        :return: The route_points of this PathItem.
        :rtype: List[RoutePoint]
        """
        return self._route_points

    @route_points.setter
    def route_points(self, route_points: List[RoutePoint]):
        """
        Sets the route_points of this PathItem.

        :param route_points: The route_points of this PathItem.
        :type route_points: List[RoutePoint]
        """

        self._route_points = route_points

