# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PathItem(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, route_id: str=None, departure_point_idx: int=None, arrival_point_idx: int=None, departure_time: str=None, arrival_time: str=None, travel_time: str=None):
        """
        PathItem - a model defined in Swagger

        :param route_id: The route_id of this PathItem.
        :type route_id: str
        :param departure_point_idx: The departure_point_idx of this PathItem.
        :type departure_point_idx: int
        :param arrival_point_idx: The arrival_point_idx of this PathItem.
        :type arrival_point_idx: int
        :param departure_time: The departure_time of this PathItem.
        :type departure_time: str
        :param arrival_time: The arrival_time of this PathItem.
        :type arrival_time: str
        :param travel_time: The travel_time of this PathItem.
        :type travel_time: str
        """
        self.swagger_types = {
            'route_id': str,
            'departure_point_idx': int,
            'arrival_point_idx': int,
            'departure_time': str,
            'arrival_time': str,
            'travel_time': str
        }

        self.attribute_map = {
            'route_id': 'route_id',
            'departure_point_idx': 'departure_point_idx',
            'arrival_point_idx': 'arrival_point_idx',
            'departure_time': 'departure_time',
            'arrival_time': 'arrival_time',
            'travel_time': 'travel_time'
        }

        self._route_id = route_id
        self._departure_point_idx = departure_point_idx
        self._arrival_point_idx = arrival_point_idx
        self._departure_time = departure_time
        self._arrival_time = arrival_time
        self._travel_time = travel_time

    @classmethod
    def from_dict(cls, dikt) -> 'PathItem':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PathItem of this PathItem.
        :rtype: PathItem
        """
        return deserialize_model(dikt, cls)

    @property
    def route_id(self) -> str:
        """
        Gets the route_id of this PathItem.

        :return: The route_id of this PathItem.
        :rtype: str
        """
        return self._route_id

    @route_id.setter
    def route_id(self, route_id: str):
        """
        Sets the route_id of this PathItem.

        :param route_id: The route_id of this PathItem.
        :type route_id: str
        """

        self._route_id = route_id

    @property
    def departure_point_idx(self) -> int:
        """
        Gets the departure_point_idx of this PathItem.

        :return: The departure_point_idx of this PathItem.
        :rtype: int
        """
        return self._departure_point_idx

    @departure_point_idx.setter
    def departure_point_idx(self, departure_point_idx: int):
        """
        Sets the departure_point_idx of this PathItem.

        :param departure_point_idx: The departure_point_idx of this PathItem.
        :type departure_point_idx: int
        """

        self._departure_point_idx = departure_point_idx

    @property
    def arrival_point_idx(self) -> int:
        """
        Gets the arrival_point_idx of this PathItem.

        :return: The arrival_point_idx of this PathItem.
        :rtype: int
        """
        return self._arrival_point_idx

    @arrival_point_idx.setter
    def arrival_point_idx(self, arrival_point_idx: int):
        """
        Sets the arrival_point_idx of this PathItem.

        :param arrival_point_idx: The arrival_point_idx of this PathItem.
        :type arrival_point_idx: int
        """

        self._arrival_point_idx = arrival_point_idx

    @property
    def departure_time(self) -> str:
        """
        Gets the departure_time of this PathItem.

        :return: The departure_time of this PathItem.
        :rtype: str
        """
        return self._departure_time

    @departure_time.setter
    def departure_time(self, departure_time: str):
        """
        Sets the departure_time of this PathItem.

        :param departure_time: The departure_time of this PathItem.
        :type departure_time: str
        """

        self._departure_time = departure_time

    @property
    def arrival_time(self) -> str:
        """
        Gets the arrival_time of this PathItem.

        :return: The arrival_time of this PathItem.
        :rtype: str
        """
        return self._arrival_time

    @arrival_time.setter
    def arrival_time(self, arrival_time: str):
        """
        Sets the arrival_time of this PathItem.

        :param arrival_time: The arrival_time of this PathItem.
        :type arrival_time: str
        """

        self._arrival_time = arrival_time

    @property
    def travel_time(self) -> str:
        """
        Gets the travel_time of this PathItem.

        :return: The travel_time of this PathItem.
        :rtype: str
        """
        return self._travel_time

    @travel_time.setter
    def travel_time(self, travel_time: str):
        """
        Sets the travel_time of this PathItem.

        :param travel_time: The travel_time of this PathItem.
        :type travel_time: str
        """

        self._travel_time = travel_time

