# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class RoutePoint(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, route_id: str=None, station_id: str=None, arrival_time: str=None, departure_time: str=None, stop_time: str=None):
        """
        RoutePoint - a model defined in Swagger

        :param route_id: The route_id of this RoutePoint.
        :type route_id: str
        :param station_id: The station_id of this RoutePoint.
        :type station_id: str
        :param arrival_time: The arrival_time of this RoutePoint.
        :type arrival_time: str
        :param departure_time: The departure_time of this RoutePoint.
        :type departure_time: str
        :param stop_time: The stop_time of this RoutePoint.
        :type stop_time: str
        """
        self.swagger_types = {
            'route_id': str,
            'station_id': str,
            'arrival_time': str,
            'departure_time': str,
            'stop_time': str
        }

        self.attribute_map = {
            'route_id': 'route_id',
            'station_id': 'station_id',
            'arrival_time': 'arrival_time',
            'departure_time': 'departure_time',
            'stop_time': 'stop_time'
        }

        self._route_id = route_id
        self._station_id = station_id
        self._arrival_time = arrival_time
        self._departure_time = departure_time
        self._stop_time = stop_time

    @classmethod
    def from_dict(cls, dikt) -> 'RoutePoint':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoutePoint of this RoutePoint.
        :rtype: RoutePoint
        """
        return deserialize_model(dikt, cls)

    @property
    def route_id(self) -> str:
        """
        Gets the route_id of this RoutePoint.

        :return: The route_id of this RoutePoint.
        :rtype: str
        """
        return self._route_id

    @route_id.setter
    def route_id(self, route_id: str):
        """
        Sets the route_id of this RoutePoint.

        :param route_id: The route_id of this RoutePoint.
        :type route_id: str
        """

        self._route_id = route_id

    @property
    def station_id(self) -> str:
        """
        Gets the station_id of this RoutePoint.

        :return: The station_id of this RoutePoint.
        :rtype: str
        """
        return self._station_id

    @station_id.setter
    def station_id(self, station_id: str):
        """
        Sets the station_id of this RoutePoint.

        :param station_id: The station_id of this RoutePoint.
        :type station_id: str
        """

        self._station_id = station_id

    @property
    def arrival_time(self) -> str:
        """
        Gets the arrival_time of this RoutePoint.

        :return: The arrival_time of this RoutePoint.
        :rtype: str
        """
        return self._arrival_time

    @arrival_time.setter
    def arrival_time(self, arrival_time: str):
        """
        Sets the arrival_time of this RoutePoint.

        :param arrival_time: The arrival_time of this RoutePoint.
        :type arrival_time: str
        """

        self._arrival_time = arrival_time

    @property
    def departure_time(self) -> str:
        """
        Gets the departure_time of this RoutePoint.

        :return: The departure_time of this RoutePoint.
        :rtype: str
        """
        return self._departure_time

    @departure_time.setter
    def departure_time(self, departure_time: str):
        """
        Sets the departure_time of this RoutePoint.

        :param departure_time: The departure_time of this RoutePoint.
        :type departure_time: str
        """

        self._departure_time = departure_time

    @property
    def stop_time(self) -> str:
        """
        Gets the stop_time of this RoutePoint.

        :return: The stop_time of this RoutePoint.
        :rtype: str
        """
        return self._stop_time

    @stop_time.setter
    def stop_time(self, stop_time: str):
        """
        Sets the stop_time of this RoutePoint.

        :param stop_time: The stop_time of this RoutePoint.
        :type stop_time: str
        """

        self._stop_time = stop_time

