# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.station import Station
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class RoutePoint(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, station: Station=None, arrival_time: str=None, departure_time: str=None, stop_time: str=None):
        """
        RoutePoint - a model defined in Swagger

        :param station: The station of this RoutePoint.
        :type station: Station
        :param arrival_time: The arrival_time of this RoutePoint.
        :type arrival_time: str
        :param departure_time: The departure_time of this RoutePoint.
        :type departure_time: str
        :param stop_time: The stop_time of this RoutePoint.
        :type stop_time: str
        """
        self.swagger_types = {
            'station': Station,
            'arrival_time': str,
            'departure_time': str,
            'stop_time': str
        }

        self.attribute_map = {
            'station': 'station',
            'arrival_time': 'arrival_time',
            'departure_time': 'departure_time',
            'stop_time': 'stop_time'
        }

        self._station = station
        self._arrival_time = arrival_time
        self._departure_time = departure_time
        self._stop_time = stop_time

    @classmethod
    def from_dict(cls, dikt) -> 'RoutePoint':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoutePoint of this RoutePoint.
        :rtype: RoutePoint
        """
        return deserialize_model(dikt, cls)

    @property
    def station(self) -> Station:
        """
        Gets the station of this RoutePoint.

        :return: The station of this RoutePoint.
        :rtype: Station
        """
        return self._station

    @station.setter
    def station(self, station: Station):
        """
        Sets the station of this RoutePoint.

        :param station: The station of this RoutePoint.
        :type station: Station
        """

        self._station = station

    @property
    def arrival_time(self) -> str:
        """
        Gets the arrival_time of this RoutePoint.

        :return: The arrival_time of this RoutePoint.
        :rtype: str
        """
        return self._arrival_time

    @arrival_time.setter
    def arrival_time(self, arrival_time: str):
        """
        Sets the arrival_time of this RoutePoint.

        :param arrival_time: The arrival_time of this RoutePoint.
        :type arrival_time: str
        """

        self._arrival_time = arrival_time

    @property
    def departure_time(self) -> str:
        """
        Gets the departure_time of this RoutePoint.

        :return: The departure_time of this RoutePoint.
        :rtype: str
        """
        return self._departure_time

    @departure_time.setter
    def departure_time(self, departure_time: str):
        """
        Sets the departure_time of this RoutePoint.

        :param departure_time: The departure_time of this RoutePoint.
        :type departure_time: str
        """

        self._departure_time = departure_time

    @property
    def stop_time(self) -> str:
        """
        Gets the stop_time of this RoutePoint.

        :return: The stop_time of this RoutePoint.
        :rtype: str
        """
        return self._stop_time

    @stop_time.setter
    def stop_time(self, stop_time: str):
        """
        Sets the stop_time of this RoutePoint.

        :param stop_time: The stop_time of this RoutePoint.
        :type stop_time: str
        """

        self._stop_time = stop_time

