# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.route_point import RoutePoint
from swagger_server.models.station import Station
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Route(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, agent_type: str=None, route_number: str=None, departure_station: Station=None, departure_time: str=None, arrival_station: Station=None, arrival_time: str=None, travel_time: str=None, periodicity: str=None, route_points: List[RoutePoint]=None):
        """
        Route - a model defined in Swagger

        :param id: The id of this Route.
        :type id: str
        :param agent_type: The agent_type of this Route.
        :type agent_type: str
        :param route_number: The route_number of this Route.
        :type route_number: str
        :param departure_station: The departure_station of this Route.
        :type departure_station: Station
        :param departure_time: The departure_time of this Route.
        :type departure_time: str
        :param arrival_station: The arrival_station of this Route.
        :type arrival_station: Station
        :param arrival_time: The arrival_time of this Route.
        :type arrival_time: str
        :param travel_time: The travel_time of this Route.
        :type travel_time: str
        :param periodicity: The periodicity of this Route.
        :type periodicity: str
        :param route_points: The route_points of this Route.
        :type route_points: List[RoutePoint]
        """
        self.swagger_types = {
            'id': str,
            'agent_type': str,
            'route_number': str,
            'departure_station': Station,
            'departure_time': str,
            'arrival_station': Station,
            'arrival_time': str,
            'travel_time': str,
            'periodicity': str,
            'route_points': List[RoutePoint]
        }

        self.attribute_map = {
            'id': 'id',
            'agent_type': 'agent_type',
            'route_number': 'route_number',
            'departure_station': 'departure_station',
            'departure_time': 'departure_time',
            'arrival_station': 'arrival_station',
            'arrival_time': 'arrival_time',
            'travel_time': 'travel_time',
            'periodicity': 'periodicity',
            'route_points': 'route_points'
        }

        self._id = id
        self._agent_type = agent_type
        self._route_number = route_number
        self._departure_station = departure_station
        self._departure_time = departure_time
        self._arrival_station = arrival_station
        self._arrival_time = arrival_time
        self._travel_time = travel_time
        self._periodicity = periodicity
        self._route_points = route_points

    @classmethod
    def from_dict(cls, dikt) -> 'Route':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Route of this Route.
        :rtype: Route
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this Route.

        :return: The id of this Route.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this Route.

        :param id: The id of this Route.
        :type id: str
        """

        self._id = id

    @property
    def agent_type(self) -> str:
        """
        Gets the agent_type of this Route.

        :return: The agent_type of this Route.
        :rtype: str
        """
        return self._agent_type

    @agent_type.setter
    def agent_type(self, agent_type: str):
        """
        Sets the agent_type of this Route.

        :param agent_type: The agent_type of this Route.
        :type agent_type: str
        """

        self._agent_type = agent_type

    @property
    def route_number(self) -> str:
        """
        Gets the route_number of this Route.

        :return: The route_number of this Route.
        :rtype: str
        """
        return self._route_number

    @route_number.setter
    def route_number(self, route_number: str):
        """
        Sets the route_number of this Route.

        :param route_number: The route_number of this Route.
        :type route_number: str
        """

        self._route_number = route_number

    @property
    def departure_station(self) -> Station:
        """
        Gets the departure_station of this Route.

        :return: The departure_station of this Route.
        :rtype: Station
        """
        return self._departure_station

    @departure_station.setter
    def departure_station(self, departure_station: Station):
        """
        Sets the departure_station of this Route.

        :param departure_station: The departure_station of this Route.
        :type departure_station: Station
        """

        self._departure_station = departure_station

    @property
    def departure_time(self) -> str:
        """
        Gets the departure_time of this Route.

        :return: The departure_time of this Route.
        :rtype: str
        """
        return self._departure_time

    @departure_time.setter
    def departure_time(self, departure_time: str):
        """
        Sets the departure_time of this Route.

        :param departure_time: The departure_time of this Route.
        :type departure_time: str
        """

        self._departure_time = departure_time

    @property
    def arrival_station(self) -> Station:
        """
        Gets the arrival_station of this Route.

        :return: The arrival_station of this Route.
        :rtype: Station
        """
        return self._arrival_station

    @arrival_station.setter
    def arrival_station(self, arrival_station: Station):
        """
        Sets the arrival_station of this Route.

        :param arrival_station: The arrival_station of this Route.
        :type arrival_station: Station
        """

        self._arrival_station = arrival_station

    @property
    def arrival_time(self) -> str:
        """
        Gets the arrival_time of this Route.

        :return: The arrival_time of this Route.
        :rtype: str
        """
        return self._arrival_time

    @arrival_time.setter
    def arrival_time(self, arrival_time: str):
        """
        Sets the arrival_time of this Route.

        :param arrival_time: The arrival_time of this Route.
        :type arrival_time: str
        """

        self._arrival_time = arrival_time

    @property
    def travel_time(self) -> str:
        """
        Gets the travel_time of this Route.

        :return: The travel_time of this Route.
        :rtype: str
        """
        return self._travel_time

    @travel_time.setter
    def travel_time(self, travel_time: str):
        """
        Sets the travel_time of this Route.

        :param travel_time: The travel_time of this Route.
        :type travel_time: str
        """

        self._travel_time = travel_time

    @property
    def periodicity(self) -> str:
        """
        Gets the periodicity of this Route.

        :return: The periodicity of this Route.
        :rtype: str
        """
        return self._periodicity

    @periodicity.setter
    def periodicity(self, periodicity: str):
        """
        Sets the periodicity of this Route.

        :param periodicity: The periodicity of this Route.
        :type periodicity: str
        """

        self._periodicity = periodicity

    @property
    def route_points(self) -> List[RoutePoint]:
        """
        Gets the route_points of this Route.

        :return: The route_points of this Route.
        :rtype: List[RoutePoint]
        """
        return self._route_points

    @route_points.setter
    def route_points(self, route_points: List[RoutePoint]):
        """
        Sets the route_points of this Route.

        :param route_points: The route_points of this Route.
        :type route_points: List[RoutePoint]
        """

        self._route_points = route_points

