# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Station(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, station_id: str=None, agent_type: str=None, station_name: str=None, country_name: str=None):
        """
        Station - a model defined in Swagger

        :param station_id: The station_id of this Station.
        :type station_id: str
        :param agent_type: The agent_type of this Station.
        :type agent_type: str
        :param station_name: The station_name of this Station.
        :type station_name: str
        :param country_name: The country_name of this Station.
        :type country_name: str
        """
        self.swagger_types = {
            'station_id': str,
            'agent_type': str,
            'station_name': str,
            'country_name': str
        }

        self.attribute_map = {
            'station_id': 'station_id',
            'agent_type': 'agent_type',
            'station_name': 'station_name',
            'country_name': 'country_name'
        }

        self._station_id = station_id
        self._agent_type = agent_type
        self._station_name = station_name
        self._country_name = country_name

    @classmethod
    def from_dict(cls, dikt) -> 'Station':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Station of this Station.
        :rtype: Station
        """
        return deserialize_model(dikt, cls)

    @property
    def station_id(self) -> str:
        """
        Gets the station_id of this Station.

        :return: The station_id of this Station.
        :rtype: str
        """
        return self._station_id

    @station_id.setter
    def station_id(self, station_id: str):
        """
        Sets the station_id of this Station.

        :param station_id: The station_id of this Station.
        :type station_id: str
        """

        self._station_id = station_id

    @property
    def agent_type(self) -> str:
        """
        Gets the agent_type of this Station.

        :return: The agent_type of this Station.
        :rtype: str
        """
        return self._agent_type

    @agent_type.setter
    def agent_type(self, agent_type: str):
        """
        Sets the agent_type of this Station.

        :param agent_type: The agent_type of this Station.
        :type agent_type: str
        """

        self._agent_type = agent_type

    @property
    def station_name(self) -> str:
        """
        Gets the station_name of this Station.

        :return: The station_name of this Station.
        :rtype: str
        """
        return self._station_name

    @station_name.setter
    def station_name(self, station_name: str):
        """
        Sets the station_name of this Station.

        :param station_name: The station_name of this Station.
        :type station_name: str
        """

        self._station_name = station_name

    @property
    def country_name(self) -> str:
        """
        Gets the country_name of this Station.

        :return: The country_name of this Station.
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name: str):
        """
        Sets the country_name of this Station.

        :param country_name: The country_name of this Station.
        :type country_name: str
        """

        self._country_name = country_name

